//--------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by a tool.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//--------------------------------------------------------------------------------------------------

#pragma warning disable 1570

using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Globalization; 
using System.Runtime.CompilerServices;

using Windows.ApplicationModel.Resources;

namespace OutdoorTracker.Resources
{
    [CompilerGenerated]
    [DebuggerNonUserCode]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0")]
    public static class Messages
    {
        private static ResourceLoader ActiveResourceLoader
        {
            get
            {
                return ResourceLoader.GetForCurrentView();
            }
        }

    }
}

#pragma warning restore 1570